# server:
#   port: 8080
  
# spring:
#   jpa:
#     hibernate:
#       ddl-auto: update
#   datasource:
#     url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/gcp
#     name: root
#     password: P@ssw0rd
    

#spring.jpa.show-sql: true

#     server.port=8080
# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/usm
# spring.datasource.username=root
# spring.datasource.password=P@ssw0rd
# spring.mail.host=mail.smart-mira.com
# spring.mail.port=587
# spring.mail.username=support@smart-mira.com
# spring.mail.password=P@ssw0rd123
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true